### ISSUE TITLE
[Deleted]?

### ISSUE THREAD

**Issue by mattaj312** [kanadaj/RoyalRoadLegends#69]
This story is either bugged or something else 
http://royalroadl.com/fiction/5651

**Comment by mattaj312** [comment]
> [Deleted] [Deleted] [Deleted] [Deleted] [Deleted] [Deleted] [Deleted] [Deleted] [Deleted] [Deleted] [Deleted] [Deleted] [Deleted] [Deleted] [Deleted] [Deleted] [Deleted] [Deleted] [Deleted] [Deleted] [Deleted] [Deleted] [Deleted] [Deleted]

**Comment by Ultrabenosaurus** [comment]
That link doesn't work, please [confirm the proper markdown syntax](https://daringfireball.net/projects/markdown/syntax#link) and correct it.

Though on the topic of this thread, I have just noticed that [The Immortal Magus](http://royalroadl.com/fiction/8441) shows up as having no chapters since the site update - though I have not contacted the author to see if this is legit and they deleted the old ones or if it is an issue from the update.

**Comment by mattaj312** [comment]
If you just paste the link http://royalroadl.com/fiction/5651 into the browser it works.

**Comment by mattaj312** [comment]
Fixed
